<a href="https://colab.research.google.com/github/Byeon-MJ/TIL/blob/main/Encoding_Label_One_Hot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 인코딩

- 머신러닝을 위한 대표적인 인코딩 방식 : 레이블 인코딩(Label Encoding) & 원-핫 인코딩(One Hot Encoding)
- 레이블 인코딩은 문자형 데이터의 피처를 unique한 코드형 숫자값으로 변환하는 방식
- 원-핫 인코딩은 피처 값의 유형에 따라 새로운 피처를 추가해 고유 값에 해당하는 컬럼에만 1을 표시하고 나머지 컬럼에는 0을 표시하는 방식

## 레이블 인코딩

- Scikit Learn의 LabelEncoder 클래스로 구현
- LabelEncoder 객체를 생성한 후 fit()과 transform()을 호출해서 수행
- 간단하게 문자열 값을 숫자형 카테고리 값으로 변환

In [2]:
from sklearn.preprocessing import LabelEncoder

items=['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

### LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행

In [6]:
# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행.
encoder = LabelEncoder()

encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


### 인코딩 클래스 확인

In [5]:
# 인코딩 클래스 확인
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


### 디코딩 원본값 확인

In [7]:
# 디코딩 원본값 확인
print('디코딩 원본값:', encoder.inverse_transform([4, 5, 2, 0, 1, 1, 3, 3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### 문제점
- 간단하게 문자열 값을 숫자형 카테고리 값으로 변환
- 숫자 값에 크고 작음에 대한 ordinal한 특성이 반영되기 독립적인 관측값간의 관계성이 생긴다.
- 몇몇 ML 알고리즘에서 가중치가 더 부여되거나 중요하게 인식하는 등, 예측 성능이 떨어지는 경우 발생
- 선형회귀와 같은 ML 알고리즘 보다는 트리 계열의 알고리즘에서 더 적합하다.


## 원-핫 인코딩(One-Hot Encoding)
- 레이블 인코딩의 문제점을 해결하기 위한 인코딩
- Scikit Learn의 OneHotEncoderEncoder 클래스로 변환 가능
- 입력값으로 2차원 데이터가 필요
- 변환한 값이 Sparse Matrix 형태이므로 toarray()를 이용해 Dense Matrix로 변환 필요
- Pandas get_dummies() 메서드를 사용하여 쉽게 변환이 가능

In [8]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']

### 2차원 ndarray로 변환

In [9]:
# 2차원 ndarray로 변환
items = np.array(items).reshape(-1, 1)

### 원-핫 인코딩 적용

In [10]:
# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

### OneHotEncoder로 변환한 결과를 밀집 행렬로 변환

In [11]:
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(7, 6)


### Pandas get_dummies() 이용

In [12]:
import pandas as pd

df = pd.DataFrame({'item':['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서', '믹서']})
pd.get_dummies(df)

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        1         0           0         0
6        0         0        1         0           0         0